export const users = [
    {
      key: "1",
      data: {
        matricule: "H9984",
        cin: "IC151153",
        nom: "AIT HADDOU",
        prenom: "Youness",
        sexe: "Male",
        type: "HC",
        dateembauche: "05/01/2025",
        datenaicessance: "05/11/2001",
        situationfamiliale: "Marié",
        score: 30,
        active: 'Active',
        email: "youness.aithaddou@ocpgroup.ma",
      },
      children: [
        {
          key: "1-0",
          data: {
            matricule: "H9984-1",
            nom: "AIT HADDOU",
            prenom: "Salma",
            sexe: "Female",
            type: "",
          },
        },
      ],
    },
    {
      key: "2",
      data: {
        matricule: "H4521",
        cin: "AB452963",
        nom: "EL MANSOURI",
        prenom: "Omar",
        sexe: "Male",
        type: "TAMCA",
        dateembauche: "12/03/2022",
        datenaicessance: "20/07/1998",
        situationfamiliale: "Célibataire",
        score: 45,
        active: 'Inactive',
        email: "omar.elmansouri@ocpgroup.ma",
      },
      children: [
        {
          key: "2-0",
          data: {
            matricule: "H4521-1",
            nom: "EL MANSOURI",
            prenom: "Amal",
            sexe: "Female",
            type: "",
          },
        },
      ],
    },
    {
      key: "3",
      data: {
        matricule: "H7643",
        cin: "ZX896321",
        nom: "BENALI",
        prenom: "Sara",
        sexe: "Female",
        type: "HC",
        dateembauche: "01/06/2024",
        datenaicessance: "11/02/2000",
        situationfamiliale: "Mariée",
        score: 60,
        active: 'Inactive',
        email: "sara.benali@ocpgroup.ma",
      },
      children: [
        {
          key: "3-0",
          data: {
            matricule: "H7643-1",
            nom: "BENALI",
            prenom: "Aya",
            sexe: "Female",
            type: "",
          },
        },
      ],
    },
    {
      key: "4",
      data: {
        matricule: "H8759",
        cin: "LM365214",
        nom: "RAHIMI",
        prenom: "Mehdi",
        sexe: "Male",
        type: "CDI",
        dateembauche: "17/09/2023",
        datenaicessance: "09/04/1995",
        situationfamiliale: "Divorcé",
        score: 75,
        active: 'Active',
        email: "mehdi.rahimi@ocpgroup.ma",
      },
      children: [
        {
          key: "4-0",
          data: {
            matricule: "H8759-1",
            nom: "RAHIMI",
            prenom: "Adam",
            sexe: "Male",
            type: "",
          },
        },
      ],
    },
    {
      key: "5",
      data: {
        matricule: "H2345",
        cin: "OP457821",
        nom: "KHALIL",
        prenom: "Mounir",
        sexe: "Male",
        type: "HC",
        dateembauche: "08/05/2021",
        datenaicessance: "15/12/1993",
        situationfamiliale: "Marié",
        score: 80,
        active: 'Active',
        email: "mounir.khalil@ocpgroup.ma",
      },
      children: [
        {
          key: "5-0",
          data: {
            matricule: "H2345-1",
            nom: "KHALIL",
            prenom: "Nour",
            sexe: "Female",
            type: "",
          },
        },
      ],
    },
    {
      key: "6",
      data: {
        matricule: "H5647",
        cin: "TY963214",
        nom: "AMRANI",
        prenom: "Lina",
        sexe: "Female",
        type: "CDI",
        dateembauche: "22/11/2020",
        datenaicessance: "03/08/1996",
        situationfamiliale: "Célibataire",
        score: 55,
        active: 'Inactive',
        email: "lina.amrani@ocpgroup.ma",
      },
      children: [],
    },
    {
      key: "7",
      data: {
        matricule: "H7865",
        cin: "GH741258",
        nom: "TAHIRI",
        prenom: "Rachid",
        sexe: "Male",
        type: "CDI",
        dateembauche: "04/07/2019",
        datenaicessance: "25/05/1990",
        situationfamiliale: "Marié",
        score: 40,
        active: 'Active',
        email: "rachid.tahiri@ocpgroup.ma",
      },
      children: [
        {
          key: "7-0",
          data: {
            matricule: "H7865-1",
            nom: "TAHIRI",
            prenom: "Meryem",
            sexe: "Female",
            type: "",
          },
        },
        {
          key: "7-1",
          data: {
            matricule: "H7865-2",
            nom: "TAHIRI",
            prenom: "Sami",
            sexe: "Male",
            type: "",
          },
        },
      ],
    },
    {
      key: "8",
      data: {
        matricule: "H9023",
        cin: "KL963258",
        nom: "HADDAD",
        prenom: "Fatima",
        sexe: "Female",
        type: "HC",
        dateembauche: "10/02/2023",
        datenaicessance: "14/01/1997",
        situationfamiliale: "Célibataire",
        score: 65,
        active: 'Inactive',
        email: "fatima.haddad@ocpgroup.ma",
      },
      children: [],
    },
    {
      key: "9",
      data: {
        matricule: "H6358",
        cin: "MN258963",
        nom: "ESSAIDI",
        prenom: "Khaled",
        sexe: "Male",
        type: "CDI",
        dateembauche: "29/04/2018",
        datenaicessance: "06/09/1988",
        situationfamiliale: "Marié",
        score: 90,
        active: 'Active',
        email: "khaled.essaidi@ocpgroup.ma",
      },
      children: [
        {
          key: "9-0",
          data: {
            matricule: "H6358-1",
            nom: "ESSAIDI",
            prenom: "Oussama",
            sexe: "Male",
            type: "",
          },
        },
      ],
    },
    {
      key: "10",
      data: {
        matricule: "H7412",
        cin: "PQ654123",
        nom: "JABIRI",
        prenom: "Nadia",
        sexe: "Female",
        type: "HC",
        dateembauche: "13/01/2025",
        datenaicessance: "21/06/1999",
        situationfamiliale: "Célibataire",
        score: 35,
        active: 'Active',
        email: "nadia.jabiri@ocpgroup.ma",
      },
      children: [],
    },
  ];

  export const Roles = [
        { name: 'Admin', code: 'ad' },
        { name: 'Createur', code: 'RM' },
        { name: 'Annimateur', code: 'LDN' },
        { name: 'Backoffice', code: 'IST' },
        { name: 'Normal utilisateur', code: 'PRS' }
    ];
  